name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@main
        with:
          github-username: rahhhmann
          filename: activity-graph.svg

      - name: Push graph
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
