name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Activity Graph
        run: |
          mkdir -p output
          curl -L -o output/activity-graph.svg "https://github-readme-activity-graph.vercel.app/graph?username=rahhhmann&theme=github-dark&bg_color=000000&color=FFFFFF&line=6E40C9&point=FFFFFF&area=true&hide_border=false"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: activity-graph-output
          cname: ""
